name: Kits
main: com.dragonphase.Kits.Kits
version: 1.3
website: http://dragonphase.com/
depend: []
description: >
             Kits plugin.
commands:
  kits:
    description: Kits help and a list of kits.
  kit:
    description: Kits help
permissions:
  kits.admin:
    description: Allows players to modify kits and reload the plugin.
    default: op
  kits.spawn:
    description: Allows players to spawn kits.
    default: op
  kits.spawn.others:
    description: Allows players to spawn kits for other players.
    default: op
  kits.bypassdelay:
    description: Allows players to bypass the kit spawn delay.
    default: op